# Generated by Django 5.2.6 on 2025-12-05 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core_RH', '0002_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='es_falta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='es_retardo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_turno', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='admin_core_RH.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('personal', 'Permiso personal'), ('medico', 'Permiso médico'), ('familiar', 'Asunto familiar'), ('estudio', 'Permiso de estudio'), ('maternidad', 'Maternidad/Paternidad'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.localdate)),
                ('aprobado_por', models.CharField(blank=True, max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='admin_core_RH.empleado')),
            ],
            options={
                'ordering': ['-fecha_solicitud', '-fecha_inicio'],
            },
        ),
    ]
