# Generated by Django 5.2.6 on 2025-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core_RH', '0003_asistencia_es_falta_asistencia_es_retardo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('remitente_nombre', models.CharField(blank=True, max_length=255)),
                ('remitente_email', models.EmailField(blank=True, max_length=254)),
                ('destinatarios', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
